/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include <stdio.h>

void GenerateInterrupt(void)
{
	uint32_t* pSTIR= (uint32_t*)0xE000EF00;
	uint32_t* pISER0= (uint32_t*)0xE000E100;

	//Enable IRQ3 Interrupt
	*pISER0 |= 1<<3;

	//Generate Software interrupt for IRQ3
	*pSTIR = (3 &0x1FF);
}

void SwitchAccessToUnprivileged(void)
{

	/*1- Read control register */
	__asm volatile("MRS R0, CONTROL");

	/*2- Modify , oring with one */
	__asm volatile("ORR R0,#0x01");

	/*3- write new value into control */
	__asm volatile("MSR CONTROL, R0");

}

int main(void)
{
	printf("In Thread mode, before interrupt\n");

	SwitchAccessToUnprivileged();

	GenerateInterrupt();

	printf("In Thread mode, after interrupt\n");

    /* Loop forever */
	for(;;);
}

void RTC_WKUP_IRQHandler (void)
{
	printf("In handler mode :  ISR\n");
}

void HardFault_Handler(void)
{
	printf("Inside HardFault handler\n");
}

